# Generated by Django 4.2.11 on 2024-04-01 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='students',
            fields=[
                ('student_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=20)),
                ('email_id', models.EmailField(max_length=100, unique=True)),
                ('phone_number', models.CharField(max_length=10, unique=True)),
                ('student_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('student_address', models.TextField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('student_dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.dept')),
            ],
        ),
        migrations.CreateModel(
            name='branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=80)),
                ('students', models.ManyToManyField(to='students.students')),
            ],
        ),
    ]
